/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Tvqbl2oDV7M
 */
import ProductCard from "@/components/product-card";
import { products } from "@/lib/products";
import Link from "next/link";
import Image from "next/image";
//import { precomputeFlags, showPromoBannerFlag } from "@/lib/flags";

export default async function Home(props: { params: Promise<{ code: string }> }) {
  const params = await props.params;

  // Precompute the promo banner flag
  //const showPromoBanner = await showPromoBannerFlag(
    //params.code,
    //precomputeFlags
  //);

  return (
    <main className="min-h-screen max-w-5xl py-6 mx-auto">
      <div className="flex flex-col">
    
        {/* Product Hero */}
        <section className="flex w-full py-8 md:py-10 lg:py-20 justify-center">
          {products[4] ? (
            <ProductHero product={products[4]} />
          ) : (
            <div className="text-center text-red-500">No featured product available</div>
          )}
        </section>

        {/* Popular Products */}
        <section className="flex flex-col w-full justify-center py-12 space-y-4 md:py-24 lg:py-32 px-4 md:px-6">
          <h2 className="text-xl font-bold tracking-tighter sm:text-2xl md:text-3xl">
            Popular Products
          </h2>
          <div className="container grid grid-cols-1 mx-auto md:grid-cols-2 lg:grid-cols-3 gap-6">
            {products.slice(1, 4).map((product, index) =>
              product ? (
                // biome-ignore lint/suspicious/noArrayIndexKey: <explanation>
            <ProductCard key={index} product={product} />
              ) : (
                // biome-ignore lint/suspicious/noArrayIndexKey: <explanation>
            <div key={index} className="text-red-500">Product not available</div>
              )
            )}
          </div>
        </section>
      </div>
    </main>
  );
}

function ProductHero({
  product,
}: {
  product: {
    slug: string;
    imageSrc: string;
    imageAlt: string;
    title: string;
    summary: string;
  };
}) {
  const { imageSrc, imageAlt, title, summary, slug } = product;

  return (
    <div className="container px-4 md:px-6">
      <div className="flex flex-col md:flex-row items-center space-y-4 md:space-y-0 md:space-x-6 text-center md:text-left">
        <Image
          alt={imageAlt}
          className="object-cover rounded-lg"
          height="500"
          width="500"
          src={imageSrc}
        />
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            {title}
          </h1>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            {summary}
          </p>
          <Link
            prefetch={true}
            className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
            href={`/product/${slug}`}
          >
            View Product
          </Link>
        </div>
      </div>
    </div>
  );
}
